/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.filepicker;

import java.util.ArrayList;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.TiActivityResultHandler;
import org.appcelerator.titanium.util.TiActivitySupport;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.util.TiIntentWrapper;

import android.app.Activity;
import android.content.ClipData;
import android.content.ContentResolver;
import android.content.Intent;
import android.net.Uri;

@Kroll.module(name="TiFilepicker", id="ti.filepicker")
public class TiFilepickerModule extends KrollModule {

    public static final String TAG = "TiFilepickerModule";

    private static ContentResolver contentResolver;

    public TiFilepickerModule()
    {
        super();

        if (contentResolver == null) {
            contentResolver = TiApplication.getInstance().getContentResolver();
        }
    }

    @Kroll.method
    public void pick(KrollDict options)
    {
        KrollFunction callback = null;

        if (options.containsKey("callback")) {
            callback = (KrollFunction) options.get("callback");
        }

        final KrollFunction fCallback = callback;

        Activity activity = TiApplication.getInstance().getCurrentActivity();
        TiActivitySupport activitySupport = (TiActivitySupport) activity;

        TiIntentWrapper galleryIntent = new TiIntentWrapper(new Intent());
        galleryIntent.getIntent().setAction(Intent.ACTION_GET_CONTENT);

        // Set media type to PDF
        galleryIntent.getIntent().setType("application/pdf");

        galleryIntent.getIntent().addCategory(Intent.CATEGORY_DEFAULT);
        galleryIntent.setWindowId(TiIntentWrapper.createActivityName("GALLERY"));

        final int PICK_IMAGE_SINGLE = activitySupport.getUniqueResultCode();
        final int PICK_IMAGE_MULTIPLE = activitySupport.getUniqueResultCode();
        boolean allowMultiple = false;

        if (options.containsKey(TiC.PROPERTY_ALLOW_MULTIPLE)) {
            allowMultiple = TiConvert.toBoolean(options.get(TiC.PROPERTY_ALLOW_MULTIPLE));
            galleryIntent.getIntent().putExtra(Intent.EXTRA_ALLOW_MULTIPLE, allowMultiple);
        }

        final int code = allowMultiple ? PICK_IMAGE_MULTIPLE : PICK_IMAGE_SINGLE;

        activitySupport.launchActivityForResult(galleryIntent.getIntent(), code, new TiActivityResultHandler() {
            @Override
            public void onResult(Activity activity, int requestCode, int resultCode, Intent data)
            {
                if (requestCode != code) {
                    return;
                }

                if ((resultCode == Activity.RESULT_CANCELED) || (data == null)) {
                    if (fCallback != null) {
                        KrollDict response = new KrollDict();
                        response.put("success", true);
                        response.put("cancel", true);
                        response.put("files", new ArrayList<String>().toArray(new String[0]));

                        fCallback.callAsync(getKrollObject(), response);
                    }
                    return;
                }

                // Fetch a URI to file selected. (Only applicable to single file selection.)
                Uri uri = data.getData();
                String path = (uri != null) ? uri.toString() : null;

                // Handle multiple file selection, if enabled.
                if (requestCode == PICK_IMAGE_MULTIPLE) {
                    // Wrap all selected file(s) in Titanium "CameraMediaItemType" dictionaries.
                    ArrayList<String> selectedFiles = new ArrayList<>();
                    ClipData clipData = data.getClipData();
                    if (clipData != null) {
                        // Fetch file(s) from clip data.
                        int count = clipData.getItemCount();
                        for (int index = 0; index < count; index++) {
                            ClipData.Item item = clipData.getItemAt(index);
                            if ((item == null) || (item.getUri() == null)) {
                                continue;
                            }
                            selectedFiles.add(item.getUri().toString());
                        }
                    } else if (path != null) {
                        // Only a single file was found.
                        selectedFiles.add(path);
                    }

                    // Copy each selected file to either an "images" or "videos" collection.

                    ArrayList<String> selectedDocuments = new ArrayList<>(selectedFiles);

                    // Invoke a callback with the selection result.
                    if (selectedDocuments.isEmpty()) {
                        if (selectedFiles.isEmpty()) {
                            // Invoke the "cancel" callback if no files were selected.
                            if (fCallback != null) {
                                KrollDict response = new KrollDict();
                                response.put("success", true);
                                response.put("cancel", true);
                                response.put("files", new ArrayList<String>().toArray(new String[0]));

                                fCallback.callAsync(getKrollObject(), response);
                            }
                        } else {
                            // Invoke the "error" callback if non-image/video files were selected.
                            String message = "Invalid file types were selected";
                            Log.e(TAG, message);
                            if (fCallback != null) {
                                KrollDict response = new KrollDict();
                                response.put("success", false);

                                fCallback.callAsync(getKrollObject(), response);
                            }
                        }
                    } else {
                        // Invoke the "success" callback with the selected file(s).
                        if (fCallback != null) {
                            KrollDict response = new KrollDict();
                            response.put("success", true);
                            response.put("files", selectedDocuments.toArray(new String[0]));
                            fCallback.callAsync(getKrollObject(), response);
                        }
                    }
                    return;
                }

                // Handle single file selection.
                try {
                    //Check for invalid path
                    if (path == null) {
                        String msg = "File path is invalid";
                        Log.e(TAG, msg);
                        if (fCallback != null) {
                            fCallback.callAsync(getKrollObject(), createErrorResponse(1, msg));
                        }
                        return;
                    }
                    if (fCallback != null) {
                        ArrayList<String> selectedDocuments = new ArrayList<>();
                        selectedDocuments.add(path);

                        KrollDict response = new KrollDict();
                        response.put("success", true);
                        response.put("files", selectedDocuments.toArray(new String[0]));

                        fCallback.callAsync(getKrollObject(), response);
                    }
                } catch (OutOfMemoryError e) {
                    String msg = "Not enough memory to get image: " + e.getMessage();
                    Log.e(TAG, msg);
                    if (fCallback != null) {
                        fCallback.callAsync(getKrollObject(), createErrorResponse(1, msg));
                    }
                }
            }

            @Override
            public void onError(Activity activity, int requestCode, Exception e)
            {
                if (requestCode != code) {
                    return;
                }
                String msg = "Gallery problem: " + e.getMessage();
                Log.e(TAG, msg, e);
                if (fCallback != null) {
                    fCallback.callAsync(getKrollObject(), createErrorResponse(1, msg));
                }
            }
        });
    }
}
